DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS text;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE text (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  art TEXT,
  subtype TEXT,
  title TEXT NOT NULL,
  link TEXT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
